# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97206e88316a70e454dda139b549d038d379caa0e326cbc7bbe1dce61b3c81934a0f7af5d4fe9fff82c4f4bf0ea0028674ea968a69c54e331d67be4db4d9a157

test:
  secret_key_base: d8accb32d734c4a881f9b0b9cbfc2fa58981d5b22c8d1cba1efe473998fd61bd79efbbd5cec804e45e86b5512a47e9608bc9514de8eea48100ba71837b0f7e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
